name: craigmcintosh
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Craig McIntosh
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#436a79'
    - '#010705'
    - '#1a363a'
    - '#dccbaf'
    - '#a4947b'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
